### ISSUE TITLE
[Bug]: Failed to perform the action number/set_value. Modbus Error: [Input/Output] ERROR: No response received after 6 retries

### ISSUE THREAD

**Issue by boredomwontgetus** [wills106/homeassistant-solax-modbus#1009]
### Describe the bug

Whenever i try to change a Setting (write a register) i get the message ```Failed to perform the action number/set_value. Modbus Error: [Input/Output] ERROR: No response received after 6 retries```.

### Integration Version

2024.08.10

### Homeassistant core version

2024.8.2

### Inverter brand

Solax Hybrid

### Plugin used

plugin_solax.py

### Serial prefix

H3UE10

### Inverter firmware versions

DSP v3.70 ARM v3.52

### Connection Method

Modbus over TCP 

### Dongle firmware

No Dongle

### Detailed Error Log
```
2024-08-21 19:56:13.540 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140580275756992] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/solax_modbus/number.py", line 151, in async_set_native_value
    await self._hub.async_write_register(
  File "/config/custom_components/solax_modbus/__init__.py", line 569, in async_write_register
    return await self.async_lowlevel_write_register(unit, address, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 562, in async_lowlevel_write_register
    resp = await self._client.write_register(address, payload[0], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 183, in async_execute
    raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 6 retries
```

**Comment by boredomwontgetus** [comment]
Sorry "Detailed Error Log" is wrong. 
This is the right one:
```
2024-08-21 19:56:13.540 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140580275756992] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 120, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/solax_modbus/number.py", line 151, in async_set_native_value
    await self._hub.async_write_register(
  File "/config/custom_components/solax_modbus/__init__.py", line 569, in async_write_register
    return await self.async_lowlevel_write_register(unit, address, payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 562, in async_lowlevel_write_register
    resp = await self._client.write_register(address, payload[0], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 183, in async_execute
    raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 6 retries
```

**Comment by boredomwontgetus** [comment]
Sorry, idiot me forgot to unlock!
