### ISSUE TITLE
[FR]: SolaX - Add support for X3-MIC with Serial Starting MU902T

### ISSUE THREAD

**Issue by CVKBaca** [wills106/homeassistant-solax-modbus#1120]
### Description

Add suport inverter type Solax X3-MIC (model: X3-9.0-T-D) SN: MU902T

### Suggested Solution

Hello It is posible add suport Solax X3-MIC sn MU902T******** mayby protocol is similar to other solax gen1.
Thanks

### Alternatives
No response

### Additional Context
Interface: Waveshare RS485 TO POE ETH (B)
![image](https://github.com/user-attachments/assets/a0d587d6-9065-4853-b2e8-099fcfb25dec)
Logger: homeassistant.config_entries
Zdroj: config_entries.py:594
Prvýkrát sa vyskytol: 08:32:58 (1 výskytov)
Naposledy prihlásený: 08:32:58

Error setting up entry SolaX for solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 188, in async_setup_entry
    await hub.async_init()
  File "/config/custom_components/solax_modbus/__init__.py", line 329, in async_init
    await asyncio.sleep(10)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 665, in sleep
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError

**Comment by CVKBaca** [comment]
With ARM firmware version 1.38 and after editing the files plugin_solax.py and plugin_solax.cpython-312.pyc, I got Modbus communication up and running.
I added the following piece of code to plugin_solax.py:

```"
elif seriesnumber.startswith('MU902T'):
    invertertype = MIC | GEN | X3 # MIC X3
    self.inverter_model = "X3-MIC""
``` 
I added the following to the plugin_solax.cpython-312.pyc file, although I'm not sure if it was necessary. :)
![image](https://github.com/user-attachments/assets/6d7e4332-9dd7-47d1-99f5-d1a5441231ac)

The result is as follows. The only sensor that didn’t load and isn’t working yet is the RTC sensor.
![image](https://github.com/user-attachments/assets/862f6a51-afbf-4a67-91e1-b4f96cc241ba)
![image](https://github.com/user-attachments/assets/d7aac87b-9ab1-433b-a11f-39a46639a252)

**Comment by wills106** [comment]
Do you perhaps need to first sync the RTC for it to return values?

**Comment by Kars-de-Jong** [comment]
Support for this serial was added in https://github.com/wills106/homeassistant-solax-modbus/commit/16cd3f2d92a01e2b0af925645d980a197017bc8f, so the issue can be closed.
