### ISSUE TITLE
[BUG] [SOLIS] Unrecognized Solis inverter type RHI-3P8K-HVES-5G

### ISSUE THREAD

**Issue by dewafre** [wills106/homeassistant-solax-modbus#433]
Im having trouble again to connect my Hybrid Solis Inverter.

In november 2022 i also had trouble with the recognition of the serial number. After reporting a bug this was solved.
I did a fresh install of HA and did a reinstall with HACS, and now having the same issue.

Thx alot for the support, this plugin is awesome!!!
So i hope there is a solution 

**Mandatory details**
1. Integration Version: Latest
2. HA Version: Home Assistant 2023.5.4
Supervisor 2023.06.1
Operating System 10.2
Frontend-versie: 20230503.3 - latest
3. Inverter Brand: Solis - RHI-3P8K-HVES-5G
4. Plugin Used: Solis
5. First 6 digits of Serial: 110C92
6. Connection Method: LAN stick

**Detailed Error Log**
2023-06-08 19:21:33.683 DEBUG (MainThread) [custom_components.solax_modbus] using pymodbus library 3.x
2023-06-08 19:21:34.068 INFO (MainThread) [custom_components.solax_modbus.config_flow] detected HA core version 2023 5
2023-06-08 19:21:34.068 INFO (MainThread) [custom_components.solax_modbus.config_flow] starting configflow - domain = solax_modbus
2023-06-08 19:21:34.069 DEBUG (MainThread) [custom_components.solax_modbus] setup entries - data: {}, options: {'name': 'Solis', 'interface': 'tcp', 'read_modbus_addr': 1, 'plugin': 'solis', 'scan_interval': 15, 'read_eps': False, 'read_dcb': False, 'read_pm': False, 'host': '192.168.1.241', 'port': 502, 'tcp_type': 'tcp'}
2023-06-08 19:21:34.069 INFO (MainThread) [custom_components.solax_modbus] trying to load plugin - plugin_name: solis
2023-06-08 19:21:34.168 DEBUG (MainThread) [custom_components.solax_modbus] Setup solax_modbus.Solis
2023-06-08 19:21:34.169 DEBUG (MainThread) [custom_components.solax_modbus] solax serial port /dev/ttyUSB0 interface tcp
2023-06-08 19:21:34.169 DEBUG (MainThread) [custom_components.solax_modbus] solax modbushub creation with interface tcp baudrate (only for serial): 19200
2023-06-08 19:21:34.170 DEBUG (MainThread) [custom_components.solax_modbus] Solis: ready to call plugin to determine inverter type
2023-06-08 19:21:34.170 INFO (MainThread) [custom_components.solax_modbus.plugin_solis] Solis: trying to determine inverter type
2023-06-08 19:21:34.189 ERROR (MainThread) [pymodbus.logging] Connection to (192.168.1.241, 502) failed: [Errno 111] Connection refused
2023-06-08 19:21:34.212 WARNING (MainThread) [custom_components.solax_modbus.plugin_solis] Solis: attempt to read serialnumber failed at 0x80ec
Traceback (most recent call last):
File "/config/custom_components/solax_modbus/plugin_solis.py", line 53, in _read_serialnr
inverter_data = hub.read_input_registers(unit=hub._modbus_addr, address=address, count=8)
File "/config/custom_components/solax_modbus/__init__.py", line 342, in read_input_registers
return self._client.read_input_registers(address, count, **kwargs)
File "/usr/local/lib/python3.10/site-packages/pymodbus/client/mixin.py", line 116, in read_input_registers
return self.execute(
File "/usr/local/lib/python3.10/site-packages/pymodbus/client/base.py", line 191, in execute
raise ConnectionException(f"Failed to connect[{str(self)}]")
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusTcpClient(192.168.1.241:502)]
2023-06-08 19:21:34.220 WARNING (MainThread) [custom_components.solax_modbus.plugin_solis] Solis: reading serial number from address 0x80ec failed; other address may succeed
2023-06-08 19:21:34.238 INFO (MainThread) [custom_components.solax_modbus.plugin_solis] Read Solis 0x80ec serial number: None, swapped: False
2023-06-08 19:21:34.239 ERROR (MainThread) [custom_components.solax_modbus.plugin_solis] Solis: cannot find serial number, even not for other Inverter
2023-06-08 19:21:34.241 ERROR (MainThread) [custom_components.solax_modbus.plugin_solis] unrecognized Solis inverter type - serial number : unknown

**Comment by alienatedsec** [comment]
@dewafre It looks like your Modbus device is not connected properly. There is no data from the inverter passed through. Is cabling ok?

**Comment by dewafre** [comment]
Yes I changed nothing, I can ping the device.
I only deleted the integration in hacs and reinstalled. Maybe the port 502
is wrong?
If I do a portscan he only finds http port 80...

Op do 8 jun. 2023 20:08 schreef alienatedsec ***@***.***>:

**Comment by dewafre** [comment]
These are the screenshots

![Screenshot_2023-06-08-20-16-31-739_io homeassistant companion android](https://github.com/wills106/homeassistant-solax-modbus/assets/64728205/bbfcf8b7-09aa-422e-964b-45d4f9bf92f3)
![Screenshot_2023-06-08-20-16-37-549_io homeassistant companion android](https://github.com/wills106/homeassistant-solax-modbus/assets/64728205/66026a28-315d-472c-933b-96209e5dfd6e)
![Screenshot_2023-06-08-20-16-44-542_io homeassistant companion android](https://github.com/wills106/homeassistant-solax-modbus/assets/64728205/80a10767-6aff-4d4f-b575-952243234db0)

**Comment by dewafre** [comment]
Ok SOLVED

The port is 8899, now I have 158 entities

**Comment by alienatedsec** [comment]
Which datalogger do you use? @dewafre 

Also, if it works, please close this issue.

**Comment by dewafre** [comment]
> Which datalogger do you use? @dewafre
> 
> Also, if it works, please close this issue.

I'm using the Solis LAN datalogger

**Comment by alienatedsec** [comment]
> I'm using the Solis LAN datalogger

Maybe I should be clearer. Which exact model? DLS-L or S2-WL-ST?

**Comment by dewafre** [comment]
> 

its a Solis-DLS-L stick
