### ISSUE TITLE
[Bug]: Solis - Hybrid: Integration hangs up on Select of Energy Control Switch

### ISSUE THREAD

**Issue by fboundy** [wills106/homeassistant-solax-modbus#818]
### Describe the bug

Solis: Integration periodically hangs up. Appears to be related to calling a Select event on the Energy Control Switch.

### Integration Version

2024.03.6

### Homeassistant core version

2024.3.3

### Inverter brand

Solis

### Plugin used

plugin_solis.py

### Serial prefix

N/A

### Connection Method

TCP Modbus with Waveshare

### Detailed Error Log

    Logger: homeassistant
    Source: /usr/src/homeassistant/homeassistant/runner.py:145
    First occurred: 22 March 2024 at 17:00:44 (3 occurrences)
    Last logged: 08:15:27
    
    Error doing job: Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))
    Traceback (most recent call last):
      File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1181, in _call_connection_lost
        super()._call_connection_lost(exc)
      File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 901, in _call_connection_lost
        self._protocol.connection_lost(exc)
      File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 288, in connection_lost
        self.__close()
    TypeError: AsyncModbusTcpClient.close() got an unexpected keyword argument 'intern'

**Comment by fboundy** [comment]
I think this *may* may the same issue as #771 so feel free to close if you think it is.

**Comment by fboundy** [comment]
I'm guessing that this related to the `pymodbus` version.  `intern` is mentioned for v3.6.6 which is included with HA v2024.3.2 so it may be that this problem is fixed for releases above that rev.  I've just upgraded to 2024.3.3 and I haven't seen it re-occur yet.
