### ISSUE TITLE
[Bug]: GROWATT' - 'SPH 10000 TL3 BH-UP' not recognized?

### ISSUE THREAD

**Issue by DorwinDT** [wills106/homeassistant-solax-modbus#834]
### Describe the bug

 I have Growatt SPH10000 TL3 BH-UP inverter and I am not able to connect to it from Solax.
via "Simply modbus TCP client" I am able to read registers, but solax is not able to connect - no devices are addedm although it doesn't write any error.

### Integration Version

2024.03.8

### Homeassistant core version

2024.3.3

### Inverter brand

GROWATT

### Plugin used

plugin_growatt.py

### Serial prefix

TPJ5CL

### Connection Method

waveshare RS485 to ETH (B)

### Additional context

2024-03-31 22:17:28.124 INFO (MainThread) [custom_components.solax_modbus] Inverter is not connected, trying to connect
2024-03-31 22:17:28.124 DEBUG (MainThread) [custom_components.solax_modbus] Trying to connect to Inverter at 192.168.131.96:502
2024-03-31 22:17:28.126 INFO (MainThread) [custom_components.solax_modbus] Inverter connected at 192.168.131.96:502
2024-03-31 22:17:28.126 INFO (MainThread) [custom_components.solax_modbus.plugin_growatt] MBGrowatt: trying to determine inverter type
2024-03-31 22:17:28.664 ERROR (MainThread) [pymodbus.logging] Unable to decode response Modbus Error: Unknown response 33
2024-03-31 22:17:28.665 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
    self.datagram_received(data, None)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
    cut = self.callback_data(self.recv_buffer, addr=addr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
    self.framer.processIncomingPacket(data, self._handle_response, slave=0)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
    self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
2024-03-31 22:17:28.667 ERROR (MainThread) [pymodbus.logging] Unable to decode response Modbus Error: Unknown response 33
2024-03-31 22:17:28.667 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 303, in data_received
    self.datagram_received(data, None)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 337, in datagram_received
    cut = self.callback_data(self.recv_buffer, addr=addr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 201, in callback_data
    self.framer.processIncomingPacket(data, self._handle_response, slave=0)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
    self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 106, in frameProcessIncomingPacket
    raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request

**Comment by DorwinDT** [comment]
problem was not in Soloax
