### ISSUE TITLE
[Bug]:  SolaX modbus integration no longer gets data

### ISSUE THREAD

**Issue by JAFC-BandO** [wills106/homeassistant-solax-modbus#872]
### Describe the bug

After updating to the new software (2024.04.3)  I'm no longer able to get any data from my SolaX modbus integration. all sensors are just unavailable. Also I tried to roll back to 
2024.04.2 previous release. It didn't fix anything 
![image](https://github.com/wills106/homeassistant-solax-modbus/assets/108722913/deac5460-6354-4dab-bacc-3071ae797f60)

### Integration Version

2024.04.3

### Homeassistant core version

2024.4.4

### Inverter brand

SolaX Power

### Plugin used

plugin_solax.py

### Serial prefix

NA

### Inverter firmware versions

NA

### Connection Method

WIFI 3.0 Adapter

### Dongle firmware

New version

**Comment by thomasrumpf** [comment]
After update to HA 2024.4.4 I have the same Problem.

**Comment by simowNgithub** [comment]
I have this issue always after fully restarting HA. Could you check what happens if you completly delete the device and add it again? I think then everything will work.

**Comment by tweltner** [comment]
> After update to HA 2024.4.4 I have the same Problem.

I have same problem after updating to HA 2024.4.4

**Home Assistant Installation:**
Core: 2024.4.4
Supervisor: 2024.04.0
Operating System: 12.2
Frontend: 20240404.2

**SolaX Integration:**
2024.04.3

**Log:**
Logger: pymodbus.logging
Quelle: custom_components/solax_modbus/__init__.py:482
Integration: SolaX Inverter Modbus ([Dokumentation](https://homeassistant-solax-modbus.readthedocs.io/), [Probleme](https://github.com/wills106/homsassistant-solax-modbus/issues))
Erstmals aufgetreten: 20:36:36 (2 Vorkommnisse)
Zuletzt protokolliert: 20:36:41

Cancel send, because not connected!

**Comment by vitjurasek** [comment]
the same problem :-(

**Comment by vitjurasek** [comment]
Tato chyba pochází z vlastní integrace.

Logger: custom_components.solax_modbus.plugin_solax
Zdroj: custom_components/solax_modbus/plugin_solax.py:7215
integrace: SolaX Inverter Modbus (dokumentace, problémy)
První výskyt: 07:47:27 (2 výskyty)
Naposledy logováno: 08:02:33

unrecognized inverter type - serial number : unknown

**Comment by ReneMronet** [comment]
same problem.

**Comment by Marc-dApice** [comment]
Same problem

**Comment by ZaphodB72** [comment]
Same problem

**Comment by tweltner** [comment]
I luckily solved the problem. After delete the configured solax integration including it's entities and re-add them directly did not help i tried yesterday this changes:

I reconfigure the existing solax integration and changed connection on second page from "Modbus TCP" to "Modbus RTU over TCP" (which is definitely not correct) - do not forget to save - and then changed this configuration back to "Modbus TCP" the connection works and all entities are back.

Maybe this helps you guys, too! :))

**Comment by ZaphodB72** [comment]
I solved it by blocking the SolaX WiFi Adapter from the Internet in my Router and then enabling Internetconnection again. 
After that all entities came back🤷‍♂️

**Comment by ReneMronet** [comment]
> I reconfigure the existing solax integration and changed connection on second page from "Modbus TCP" to "Modbus RTU over TCP" (which is definitely not correct) - do not forget to save - and then changed this configuration back to "Modbus TCP" the connection works and all entities are back.

Thanks @tweltner!
That helps for me :-)

Best regards

**Comment by he-tim** [comment]
Same issue here after rebooting HA. 
SolaX integration was running fine for several weeks before.
I am using 2 SolaX systems with Wifi Dongles - both connections failed at the same time.
Reconfiguring the integration from "Modbus TXP" to "Modbus RTU (or ASCII) over TCP" and back did not change anything.
HA:
  - Core 2024.4.4
  - Supervisor 2024.04.0
  - Operating System 12.2
  - Frontend 20240404.2

**Comment by Codiwr** [comment]
Same problem here -

Hard reset of the inverter seems to have worked
- unplugged dongle, plugged back in then turned off and on. Then reloaded (not reinstalled) integration.

- Other suggestions above failed as well as restoring HA from backup from a few days ago.
Hope this helps

**Comment by JAFC-BandO** [comment]
**Workaround**:

I fixed my issue by rebooting my main router and retriggering the HA SolaX integration setup with the "new" IP that was assigned to the inverter.

**Comment by Lake292** [comment]
Same here yesterday my HA was updated and today I have hard time to reestablishing the connection again... Solax Cloud works also other applications that use Modbus TCP are working fine.

**Comment by ernst10** [comment]
Just a short update.
I did rollback to core 2024.4.0 now the Modbus is working again. I used Terminal and the following command:
ha core update --version 2024.4.0. I had to wait a few minutes as i use a Microsd card for HA.
on another test system having the same problem i did also rollback to 2024.4.0 and also worked. Then i did update to 2024.4.4 which as the failing core version before and surprise it worked again with 2024.4.4
don´t know what is there going on

Ernst10

**Comment by Codiwr** [comment]
Broken again :(. Not found a solution yet

**Comment by hansaugler** [comment]
Same problem with With Waveshare RS485 Server

**Comment by ernst10** [comment]
was anyone able to verify my "solution" ? for me it´s still working. Yes i will not do any update to 2024 .5.x. What a surprise. 
Ernst10

**Comment by johnnyhero83** [comment]
I kind of have the same problem. Sometimes I am able to load the entities and sometimes not. While doing nothing differently. It seems like it is randomly going through once and second time you just cant load them. Plus it seems like after you can finsky read the data, you cant write over modbus. The entity Solax.Lock.State seems to be Locked and not Unlocked. Then you cant write.

**Comment by johnnyhero83** [comment]
Have any of you guys has it solved by updating to Ha core 5.1.?
Or updating to version 5.2. Of this custom integration?
Thanks

**Comment by Codiwr** [comment]
I upgraded to core 5.1.0 - and it's working now, not sure if that was what fixed it directly though.

**Comment by ernst10** [comment]
Hi 
Is there a way for rollback to previous version of the modbus custom integration. Just to know before i will test with latest version 5.2

thanks
Ernst10

**Comment by Strinzer** [comment]
Fallback to 2024.4.0 and update to 2024.4.4 (like ernst10) worked for HA OS instance. It did not work for Supervised Version.

**Comment by ernst10** [comment]
Strange. I´m running supervised version of HA

**Comment by ernst10** [comment]
Update
using supervised HA
upgrade from Core 2024.4.4 to core 2024.5.1 
Modebus still working
now upgrade modbus solax 2024.4.3 to 2024.5.2
all is working again as expected

what ever has caused the break it is gone now for me

ernst10

**Comment by simowNgithub** [comment]
> Update using supervised HA upgrade from Core 2024.4.4 to core 2024.5.1 Modebus still working now upgrade modbus solax 2024.4.3 to 2024.5.2 all is working again as expected
> 
> what ever has caused the break it is gone now for me
> 
> ernst10

core 2024.4.4
solax 2024.5.2

working also on my system.

**Comment by Codiwr** [comment]
Problem has returned again. On HA 5.1. Upgraded to 5.2 but to no avail. Restarting/rebooting jas had no effect.

**Comment by purewhitedesign** [comment]
I don't know, whats going on. After update to solax inverter modbus 2024.05.2 all entities are not available. So I restore a backup and it works. Today same issue. No entities available.
Solutions like change TCP to RTU and back or block / allow internet access doesn't work for me.
I had to delete the solax interverter modbus integration completely. Then I installed and configured it again.
Now it works.
Solax Version: 2024.05.2
Core: 2024.5.2
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

**Comment by Codiwr** [comment]
Has happened 3 times over the past week. Only thing that works reliably is to Unbind in Solax app, turn off hard switch on Inverter and on again and set up WiFi again in app. 

Then restart Solax integration and restart HA. No need to delete/clear HA data.

**Comment by Marc-dApice** [comment]
So I've completely built a new Home Assistant (supervised) server from scratch to try and eliminate any current configuration issues and I am still not able to connect.
I have noticed that the interface on the pocket wifi/inverter has at some stage updated and is now running firmware version.

SolaX Firmware: 3.001.02.
HAOS: 12.3
Core: 2024.5.3


My error is:

Logger: custom_components.solax_modbus.plugin_solax
Source: custom_components/solax_modbus/plugin_solax.py:68
integration: SolaX Inverter Modbus ([documentation](https://homeassistant-solax-modbus.readthedocs.io/), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 16:07:28 (1 occurrences)
Last logged: 16:07:28

SolaX: attempt to read serialnumber failed at 0x0 data: None
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/plugin_solax.py", line 68, in async_read_serialnr
    inverter_data = await hub.async_read_holding_registers(unit=hub._modbus_addr, address=address, count=7)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 483, in async_read_holding_registers
    resp = await self._client.read_holding_registers(address, count, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 183, in async_execute
    raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries

**Comment by ReneMronet** [comment]
@Marc-dApice
There is a newer firmware for the Pocket Wifi (3.015.02)
And flash the newest for the inverter too.

**Comment by Codiwr** [comment]
I do wonder if the error is coming from the Solax end (Modbus failure)
rather than the integration.

Do you still have to email tech support to get inverter updates, crazy!

**Comment by ReneMronet** [comment]
Hier gibt es die neusten Firmware Updates für alle SolaX Komponenten.
Aber passet genau auf, welche Hardware ihr habt!

[https://app.box.com/s/3nvo7ic523fhojf8uuto105q9a8dgk9n/folder/79352264617](url)

**Comment by anton4** [comment]
It is not SolaX issue as other inverters (Sofar eg.) have the same exact problem.

**Comment by ReneMronet** [comment]
I have both SolaX and Sofar inverters with the latest firmware and only had the problems with the SolaX.

Of course, there could be several reasons for this.

**Comment by Strinzer** [comment]
updated Home Assistant Core to  2024.5.3 and Solax Inverter Modbus to 2024.05.3, delete Solax Hub and added it again and everythings works fine. 1 device and 221 entities are there and data collected from the Solax system and shown in HA.

**Comment by Strinzer** [comment]
problem is there again :-(

**Comment by purewhitedesign** [comment]
Same here. It runs for a few days - see https://github.com/wills106/homeassistant-solax-modbus/issues/872#issuecomment-2104997073.
And today it doesn't work again.

**Comment by wills106** [comment]
As long as you name the Inverter the same in the Integration it will pick up all of the history.

**Comment by ernst10** [comment]
The following System was now running for about 2 weeks
using supervised HA
upgrade from Core 2024.4.4 to core 2024.5.1
Modebus still working
now upgrade modbus solax 2024.4.3 to 2024.5.2

Now it has crashed over night 
Updating HA core and system doesn´t help
Updating SolaxModbus doesn´t work
removing the Integration restart and add again doesn´t work

That´s a real bad situation as i wanted to use the integration to manage power what is just not consumed by the houseload to use an electrical power heater to heat my water boiler

Does anyone know a real working solution

Thanks Ernst10

**Comment by ernst10** [comment]
I do have two different HA system running on two Raspi.
the one having the following versioning
using supervised HA
upgrade from Core 2024.4.4 to core 2024.5.1
Modebus still working
now upgrade modbus solax 2024.4.3 to 2024.5.2

this stopped now for about 6 hours and now started working again, without manuell intervention.
The second system has been updated today on all available new versions. Even restart doesn´t worked. 
Interesting situation, as the "old" system started working again, this one with latest updates started working as well round about the same time after a new restart of HA.

I´m wondering what has stopped working and why started again . Could there be any kind of missmatch for some time in the Solax Modbus system, not the integration?
thanks.

Ernst10

**Comment by SteffenMichalke** [comment]
I switched back from the latest version to 2024.4.3 and both systems are running. In the latest version my X1 Mini was down, the X1 G4 Hybrid was fine. I have no idea, but I think if the system is good, don't change it. (or: “never touch a running system”)
What is the reason to upgrade if the system is fine?

**Comment by wills106** [comment]
@SteffenMichalke for your Mini you will be getting the same error as #907 I think.
Just working on a fix.

**Comment by SteffenMichalke** [comment]
THX for your answer. I think, if my system works, then it‘s fine and I don‘t need an update. 
If you solve the problem in a next version, I will read the documentation and decide for an update. 
But - all in all - good work. Thanks for the implementation.

**Comment by ernst10** [comment]
@Steffen
Even when the system is running and you don´t do any updates on any integration or OP system, you may end suddenly on a not working modebus integration. you may have a look at my comments above where i described just this kind of situation. You need to go back to this beginning https://github.com/wills106/homeassistant-solax-modbus/issues/872#issuecomment-2088895010 of my comments.

@wills106 
do you work on a global fix for all open issues, as i have the feeling that there are some open "Bugs" with the same root cause perhaps. 
Can you imagine why system get stopped and worked again after several hours of "out of order" as i wrote in my last comment?

thanks
Ernst10

**Comment by SteffenMichalke** [comment]
@ernst10 
BTW: I manage my power for the electrical water heater over a Power Genius 3000 and a solid state relais, out of HA via ModBus RTU directly from the inverter. Runs perfect.

**Comment by ReneMronet** [comment]
Hi folks,
I wanted to give you some more information.

I have two X3-Hybrid-15 inverters in two different houses.

Yesterday I added more integrations to Home Assistant and configured them.
I also made a few changes to the SolaX Inverter Modbus integration. (Changed the name of the two devices)

I then noticed that Home Connect (Siemens) and the SolaX Inverter Modbus integration are no longer working. (No more data was delivered.

After restarting Home Assistant, Home Connect worked again, but the SolaX Inverter Modbus Integration did not receive any data from either inverter.

Unfortunately, downgrading the Solax Inverter Modbus Integration or reinstalling etc. did not help.

The only thing that helped was unplugging and plugging in the Pocket-Wifi V3.0 or, in the case of the second inverter, unplugging and plugging in the Pocket-Wifi+LAN V3.0.
Both Pocket are integrated into the home network via WLAN.

Data was sent again after approx. 30 seconds.

All SolaX components (inverter, Pocket-Wifi and Pocket-Wifi+LAN) have the latest firmware version.

SolaX Inverter Modbus Version: 2024.05.5
HACS: 1.34.0
Home Assistant:
Core: 2024.5.4
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

All integrations are currently working normally again.

LG
Rene

**Comment by mc4wrk** [comment]
> ### Describe the bug
> After updating to the new software (2024.04.3) I'm no longer able to get any data from my SolaX modbus integration. all sensors are just unavailable. Also I tried to roll back to 2024.04.2 previous release. It didn't fix anything ![image](https://private-user-images.githubusercontent.com/108722913/325245450-deac5460-6354-4dab-bacc-3071ae797f60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NDQxMDEsIm5iZiI6MTcxNjU0MzgwMSwicGF0aCI6Ii8xMDg3MjI5MTMvMzI1MjQ1NDUwLWRlYWM1NDYwLTYzNTQtNGRhYi1iYWNjLTMwNzFhZTc5N2Y2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwOTQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTZmMTA5NzIyNmE0OGM5ZmUzZGNlY2U1Mzg2NTFkZTFkM2QyZGI5N2MzZTdhMDJmYmQzODcwZjAwMzY4ZDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VtRy0-VhHeLGC-aJlRsX73IrFOmet6X3LDhIz-yWHlI)
> 
> ### Integration Version
> 2024.04.3
> 
> ### Homeassistant core version
> 2024.4.4
> 
> ### Inverter brand
> SolaX Power
> 
> ### Plugin used
> plugin_solax.py
> 
> ### Serial prefix
> NA
> 
> ### Inverter firmware versions
> NA
> 
> ### Connection Method
> WIFI 3.0 Adapter
> 
> ### Dongle firmware
> New version
> 
> ### Detailed Error Log
> _No response_
> 
> ### Additional context
> _No response_

Same here.
After update all my sensors are gone. :(
I'm very sorry but I only use this integration to check the system "Locally". 
Thank you for your support.

**Comment by Codiwr** [comment]
This is still happening to me about every 72 hours, despite all the
suggested solutions.

Temporary solution is straightforward- unbind, repair on router and restart
HA, but can only be done if home with local WIFI connection to the router.

Still hoping on a proper fix

**Comment by Codiwr** [comment]
Inverter not router*

**Comment by wills106** [comment]
The Wiki does mention [unplugging PocketWiFi](https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-faq/#i-have-lost-my-entities-on-restart-update-using-pocketwifi-30) when it stops working. I don't own a PocketWiFi device so I don't know what's wrong with them.

For people having this issue are you on an older [Firmware Version](https://homeassistant-solax-modbus.readthedocs.io/en/latest/solax-faq/#how-to-find-firmware-version) for your PocketWiFi?

Possibly fixed in later Firmware versions.

**Comment by SteffenMichalke** [comment]
Pocket WiFi is not the problem. With newest core 2024.5.5 and SolaX 2024.5.5 x1 Mini is fine and x1 hybrid G4 gets no data.  Via a Modbus software datapoints are available. 
I have no idea.

**Comment by SteffenMichalke** [comment]
Restart the WiFi dongle - same problem -  login via browser. Everything is ok. Switch my screen to HA. Now it works. 
Why? - I don’t know.

**Comment by Codiwr** [comment]
Lasted less than 48hrs before losing entities this time, have upgraded
inverter, pocket wifi, integration and HA to latest versions

**Comment by ernst10** [comment]
@wills106 
The pocket WIFI is not generating the problem.
I do have two HA running side by side and both are connecting to the same pocket WIFI. 
Just a few hours ago, one system lost connection and sensors are lost. The second system is just running fine. the system "down" is on latest version for HA and integration and worked fine as well.

thanks Ernst10

**Comment by SteffenMichalke** [comment]
I think, one hole is closed, a second is opened. 
My systems are running now - both. We will see. 
It remains exciting.

**Comment by SteffenMichalke** [comment]
This morning - same problem, X1 Hybrid G4 was down, X1 Mini was running. Restart the wifi dongle, delete the hub and reinstall - works. But how long?

**Comment by Codiwr** [comment]
Unplugging the dongle and reloading the integration without HA restart
worked today!

Just changed DHCP to static ip in case that makes a difference (although
never seen the ip address change previously)

**Comment by ernst10** [comment]
Restored backup from second HA on failing system and it´s working now again. Have not changed any TCP parameter or what else

**Comment by purewhitedesign** [comment]
Just want to keep you informed. 
After updating a few components and integrations it works flawlessly:

**Solax Version: 2024.05.7
Core: 2024.5.5**
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1

**Comment by ReneMronet** [comment]
Hi folks,
one way to get SolaXModbus working again in Home Assistant is to log in to the PocketWifi dongle and reset the password. Either a new password or enter the same one again - please test it yourself. For me it only worked with a new password. I later re-entered my old password.
After that, everything worked again in the Home Assistant.

Perhaps the problem is due to updates in the Home Assistant and the many queries to the PocketWifi dongle - which receives too many requests at the same time and crashes. But that's just a guess.

But for those who are not on site and cannot unplug the Pocket Wifi dongle and then plug it back in, this should be a quick hack to get everything working again.

Greetings

**Comment by wills106** [comment]
It must power cycle the PocketWiFi when you change the password.

I'm guessing there isn't a reboot option in the Interface of the PocketWiFi?

**Comment by wills106** [comment]
It might be worth trying a [multiplexer?](https://github.com/wills106/homeassistant-solax-modbus?tab=readme-ov-file#multiple-connections)

Connect the multiplexer to the PocketWiFi, then connect HA to the Multiplexer.
That way the main connection to the PocketWiFi is consistent.

**Comment by ReneMronet** [comment]
> I'm guessing there isn't a reboot option in the Interface of the PocketWiFi?

No - unfortunately not.
That's why you need to change the password.

**Comment by ReneMronet** [comment]
> It might be worth trying a [multiplexer?](https://github.com/wills106/homeassistant-solax-modbus?tab=readme-ov-file#multiple-connections)
> 
> Connect the multiplexer to the PocketWiFi, then connect HA to the Multiplexer. That way the main connection to the PocketWiFi is consistent.

That might be a solution.
Please test it and let us know.

Thank you very much!

**Comment by ernst10** [comment]
Hi 
could the multiplexer be installed on one of the HA supervised Installation? As far as I know, the supervised HA is not a 100% docker .
If some one would have an installation info i could give it a test on one of my two HA 
many thanks
Ernst10

**Comment by beakable** [comment]
Long shot as I’m in the middle of working out any pattern to it sporadically stopping to work - but have you got it registered with the Solax app/site as well?

Since adding it to HA, the Solax app no longer showed any data, no matter if trying to reregister it or using a different pocket dongle. It’s been this way since day one for me.

Solax to HA went down after about 5 hours for me, after already going down earlier today and being fixed by unplugging the plugging the dongle back in.  I’ve been messing with new automations so I wasn’t sure if that’s related… 

… however I randomly noticed that when it was down on HA, it had started working with the Solax app. I’ve tried I registering with the Solax app to see the outcome. 

Side note, trying to update the password via the pocket dongle lan IP to bring it back doesn’t work for me - only a hard reset by unplugging it from the inverter, which brings it back on HA within a minute or so.

**Comment by beakable** [comment]
I've tried greatly reducing the number of entities enabled to the bare minimum I require for daily monitoring and my automations - I'm not sure if entity count impacts and to what level, however it's now on day 3 without going down. Over the 5 days prior it was going down every 10~ hours - could just be coincidence.

My current entity enabled list - 

solar System On - button.solar_system_on
solar System Off - button.solar_system_off
solar Charger End Time 1 - select.solar_charger_end_time_1
solar Charger End Time 2 - select.solar_charger_end_time_2
solar Charger Start Time 1 - select.solar_charger_start_time_1
solar Charger Start Time 2 - select.solar_charger_start_time_2
solar Charger Use Mode - select.solar_charger_use_mode
solar Device Lock - select.solar_device_lock
solar Selfuse Night Charge Enable - select.solar_selfuse_night_charge_enable
solar Run Mode - sensor.solar_run_mode
solar Battery Power Charge - sensor.solar_battery_power_charge
solar Battery Capacity - sensor.solar_battery_capacity
solar Grid Export - sensor.solar_grid_export
solar Grid Import - sensor.solar_grid_import
solar House Load - sensor.solar_house_load
solar PV Power Total - sensor.solar_pv_power_total

**Comment by Xelaroom** [comment]
I had the same issue with the sudden loss of readings without any changes to the existing system. The readings are transmitted via modbus and waveshare.

The following has been tried WITHOUT success:
Update HA
Update Solax integration
Update Solax firmware
Changes to the dongle
Router changes

Only after a reset of waveshare everything works fine again. However, I don't know what caused the failure.

**Comment by simowNgithub** [comment]
I had exactly the same issues. 

After routing the modbus signal through the modbusproxy, everything is working now without any crashes. 

The issue is if you have more than one service communicating with the solax modbus port.

**Comment by ernst10** [comment]
Hi,
Just some  ideas.
I had a look at the network traces from Strinzer. As the working situation does not show SYN SYNack Ack for starting the communication it can´t be verified against the non-working traces. What could be seen is that by non-working the Solax is accepting the connection but a few milliseconds later it is closing the connection.
As we can see from different user that they have trouble with direct Modbus/TCP and also Modbus Wafeshare which is on a different connection layer RS 485 I can´t correlate the issue and can´t see what Modbusproxy will help here.
Simon can you provide info about Modbusproxy and how it is connected Modbus/TCP. What are the two HA station or what else connected. How is Modbusproxy installed and on what hardware.
Many thanks
Ernst10

Von: Simon ***@***.***>
Gesendet: Freitag, 21. Juni 2024 22:32
An: wills106/homeassistant-solax-modbus ***@***.***>
Cc: ernst10 ***@***.***>; Mention ***@***.***>
Betreff: Re: [wills106/homeassistant-solax-modbus] [Bug]: SolaX modbus integration no longer gets data (Issue #872)


I had exactly the same issues.

After routing the modbus signal through the modbusproxy, everything is working now without any crashes.

The issue is if you have more than one service communicating with the solax modbus port.

**Comment by Codiwr** [comment]
What I don't understand is that it was working fine for 6 months, around 6
weeks ago it started dropping out about 3 times a week.

Only connected to Solax app and Home Assistant (aa single device) and
nothing has changed since original installation. So there must be some
software conflict following updates somewhere whether HA, integration,
modbus or Solax.

**Comment by ernst10** [comment]
@ Simon,

Could you please give some more deatil about Modbusproxy.
Could it be installed on one of the HA supervised instances? and how will connect this instance then to the proxy. The second HA instance should be clear to direct it to the proxy.

Many thanks
Ernst10

**Comment by berndzimek** [comment]
Hi 
Had the same problem - HA did not see the sensors anymore.
I blocked now the IP connection to the cloud in my router. This solves the issue for me and I do not need the cloud ...

**Comment by ernst10** [comment]
Hi just now my two system dropped connection between Solax and HA using Modbus / TCP connection from wills106.
when thinking about Modbus Proxy, i´m wondering how it should help, as i had alreadey dropped connection when i had only one system at start. The second has been configured and used few mounth later.
So the only i can think of is, that the WIFI Dongle connecting to Solax Cloude and the HA Modbus TCP are using the same TCP port from SOLAX . If this will be correct, I´m not sure what a  Proxy can help here. The WIFI Dongle is direct attached to SOLAX using USB, so no way to redirect it to the proxy at all.
Does any one know if Modbus RTU Waveshare is working with SOLAX and also the DTSU666 smart meter. As the DTSU is using RS485 already and Waveshare would use the same wire. I guess there will be an Master Slave issue, as we then have two Master on the wire, as one will be SOLAX and the other would be Waveshare, as far as i know.

many thanks
Ernst10

**Comment by ernst10** [comment]
Now short update
Had shutdown both system completly
disconnected WIFI from SOLX
wait one minute
connect WIFI again
restart of one HA need to wait for new data after message HA started sucessfully about one minute
works again
same procedure for second system, now also running again

Thanks
Ernst10

**Comment by berndzimek** [comment]
With blocked IP HA was able to access the Solax.
I removed the IP blocker again and after a view hours HA did not see the Solax Entities anymore.
Shutdown as described from ernst10 helps - but I am afraid it works again only for some time.

I would like to try the multiplexer solution - but I am not able to set it up. 
I simply don't know how to. Could someone describe how I can set this up in HA ?

**Comment by ernst10** [comment]
Had some more research about WIFI Dongle
Found that WIFI V3 with serial number starting with SV or SR are not able for 10 Second update interval..
I do have a SR Wifi
So may be that is an indication about why it´s stopping .
Can someone verify and comment this findings? Does anyone have a WIFI V3 with not starting serial number with SV or SR and still having the known issue. May be this can help here. 
I read the Cloud data every 5 minutes in addition to HA data and cloud never stopped.
So if we can verify that clout 10 second interval is working fine we can probably change the connection from HA to cloud 

thanks 
Ernst10

**Comment by berndzimek** [comment]
My dongle SN starts with SR... 
Cloud also never stopped. HA stopped after few hours -  but my HA update interval was set to 15s which was the default.

**Comment by simowNgithub** [comment]
> @ Simon,
> 
> Could you please give some more deatil about Modbusproxy. Could it be installed on one of the HA supervised instances? and how will connect this instance then to the proxy. The second HA instance should be clear to direct it to the proxy.
> 
> Many thanks Ernst10

@ernst10 sorry for the late late response, please do the @ with my name, i didn't saw the notification belongs to me. 

1. i installed on home assistent the addon "modbus-proxy"
2. i stopped every connection of the solax inverter
3. i connected the addon modbus-proxy with the solax inverter
4. i reconfigured home assistant to get entity values from the modbus-proxy-server-ip (home assistant ip...), also for the evcc

while the modbus-proxy get the signal of the solax inverter, i did at least one restart of the wifi/lan pocket adapter after my last post. it is working fine. before (without the modbus-proxy) i had to restart the wifi/lan pocket every day because the issue is that the solax wifi/lan pocket can not communicate with two or three modbus-clients.

**Comment by ReneMronet** [comment]
> > @ Simon,
> > Could you please give some more deatil about Modbusproxy. Could it be installed on one of the HA supervised instances? and how will connect this instance then to the proxy. The second HA instance should be clear to direct it to the proxy.
> > Many thanks Ernst10
> 
> @ernst10 sorry for the late late response, please do the @ with my name, i didn't saw the notification belongs to me.
> 
> 1. i installed on home assistent the addon "modbus-proxy"
> 2. i stopped every connection of the solax inverter
> 3. i connected the addon modbus-proxy with the solax inverter
> 4. i reconfigured home assistant to get entity values from the modbus-proxy-server-ip (home assistant ip...), also for the evcc
> 
> while the modbus-proxy get the signal of the solax inverter, i did at least one restart of the wifi/lan pocket adapter after my last post. it is working fine. before (without the modbus-proxy) i had to restart the wifi/lan pocket every day because the issue is that the solax wifi/lan pocket can not communicate with two or three modbus-clients.

Could you please provide a link to the ModbusProxy?

Thx
Greetings

**Comment by simowNgithub** [comment]
https://github.com/Akulatraxas/ha-modbusproxy

**Comment by ReneMronet** [comment]
@simowNgithub

Thanks a lot! :-)

**Comment by ReneMronet** [comment]
@simowNgithub
Hello again,
would it also be possible to get values from two SolaX inverters into the Homa Assistannt via the ha-modbusproxy?

Thanks alot for the information!
Greetings

**Comment by simowNgithub** [comment]
> @simowNgithub Hello again, would it also be possible to get values from two SolaX inverters into the Homa Assistannt via the ha-modbusproxy?
> 
> Thanks alot for the information! Greetings

Yes, i only changed the ip‘s… my HA is asking himself on port 502 and get there the values from the modbusproxy. Also the evcc is asking the HA ip with port 502. and the HA modbusproxy is the only service who really connects to the solax inverter. so you have one open connection to solax and the proxy broadcasts the modbus values everywhere.

**Comment by ReneMronet** [comment]
@simowNgithub 
Cool! Thanks for the information :-)

Can I still use the SolaX Inverter Modbus Integration - or do I have to create all entities again?

Greetings

**Comment by simowNgithub** [comment]
For me, it was only changing ip. But not sure about our complete setup. Backup HA, try, and you will see ;)

**Comment by ReneMronet** [comment]
@simowNgithub
OK - I'll test it and report back here :-)
Thx

**Comment by mc4wrk** [comment]
HI,

 

My integration is back online, since last week, after a month interruption due to an HA update.

Everything is working fine since last Friday. 

 

Thank you 

All the Best

Mario

**Comment by ReneMronet** [comment]
@simowNgithub
With a fork of ha-modbusproxy you can enter up to 3 Modbus clients.

[](https://github.com/TCzerny/ha-modbusproxy)

This is not possible with the “standard” version.

**Comment by ernst10** [comment]
Hi there
Please appologize my comment, if i´m wrong
When having a look at the beginning of this thread, we can see that even one Modebus integration from wills106 stopped working suddenly 
here my question now :  How can solve Modbus Proxy or what else solve the issue?
Proxy du help  connecting more that one client to one WIFI, may be, but the reale problem seem to be that already one connection get broken, see beginning of this issue.
For me proxy is not the game changer.
Another question:  does anyone have info how to trace network traffic on Hassion container / docker ?
tried tcpdump but does not get real traffic 

thanks a lot Ernst10

**Comment by ReneMronet** [comment]
@ernst10
as we try to find the error here and point out solutions.
I realize that the error will not be fixed - but perhaps it will help one or the other to make improvements.

I believe that the problem is caused by too many requests to the Modbus on the SolaX inverter.

If you restart the Home Assistant too often, for example because you are testing and setting up a new integrity and the Home Assistant is restarted too often - then it can happen that the Modbus on the SolaX inverter "hangs up".

It could help if you deactivate the inverter(s) in the "Solax Inverter Modbus" integration during such tests.

The proxy is also just a test for me - I have not looked in detail at how it was programmed, but if it caches values, then this could reduce the number of requests to the SolaX inverter Modbus and thus prevent the "crash".

It might be an advantage if the individual values in the "Solax Inverter Modbus" integration are queried with a longer time interval when Home Assistant is restarted.

But I am sure that we will all find a permanent solution together :-)

Translated with DeepL.com (free version)

**Comment by samuelg0rd0n** [comment]
> If you restart the Home Assistant too often, for example because you are testing and setting up a new integrity and the Home Assistant is restarted too often - then it can happen that the Modbus on the SolaX inverter "hangs up".

I think that in my case it was definitely caused by this. I tested new RESTful configuration, restarted too often and then suddenly the integration stopped working. At first, I tried removing the devices/entities and re-adding them again but it didn't work. The configuration just hung up. So I took out the dongle from the inverter, waiting like 15 seconds and put it back. Then tried to configure the integration and it worked like a charm. All my entities are back 😊
