### ISSUE TITLE
[Bug]: Cancel send, because not connected!

### ISSUE THREAD

**Issue by JaroslavHorky** [wills106/homeassistant-solax-modbus#901]
### Describe the bug

Hello, This afternoon after restarting HA, my Solax entities disappeared.
I found these errors in the log:

- Cancel send, because not connected!
- SolaX: attempt to read serialnumber failed at 0x0 data: None
- SolaX: attempt to read serialnumber failed at 0x300 data: None
- SolaX: reading serial number from address 0x0 failed; other address may succeed
- SolaX: reading serial number from address 0x300 failed; other address may succeed
- SolaX: cannot find serial number, even not for MIC
- unrecognized inverter type - serial number : unknown

Tried restarting HA, Solax. Nothing helped.
What could be the problem? Thanks

I'm sorry if I'm missing some information there. I didn't find them.

### Integration Version

2024.05.4

### Homeassistant core version

2024.5.4

### Inverter brand

Solax X3-Hybrid-G4

### Plugin used

plugin_solax.py

### Serial prefix

???

### Inverter firmware versions

???

### Connection Method

USB dongle Pocket WiFi Plus

### Dongle firmware

3.001.02

### Detailed Error Log

Tato chyba pochází z vlastní integrace.

Logger: pymodbus.logging
Zdroj: custom_components/solax_modbus/__init__.py:482
integrace: SolaX Inverter Modbus (dokumentace, problémy)
První výskyt: 15:41:13 (2 výskyty)
Naposledy logováno: 15:41:18

Cancel send, because not connected!

Tato chyba pochází z vlastní integrace.

Logger: custom_components.solax_modbus.plugin_solax
Zdroj: custom_components/solax_modbus/plugin_solax.py:7002
integrace: SolaX Inverter Modbus (dokumentace, problémy)
První výskyt: 15:41:18 (1 výskyty)
Naposledy logováno: 15:41:18

unrecognized inverter type - serial number : unknown

Tato chyba pochází z vlastní integrace.

Logger: custom_components.solax_modbus.plugin_solax
Zdroj: custom_components/solax_modbus/plugin_solax.py:6925
integrace: SolaX Inverter Modbus (dokumentace, problémy)
První výskyt: 15:41:18 (1 výskyty)
Naposledy logováno: 15:41:18

SolaX: cannot find serial number, even not for MIC

### Additional context

Logger: custom_components.solax_modbus.plugin_solax
Zdroj: custom_components/solax_modbus/plugin_solax.py:80
integrace: SolaX Inverter Modbus (dokumentace, problémy)
První výskyt: 15:41:13 (2 výskyty)
Naposledy logováno: 15:41:18

SolaX: reading serial number from address 0x0 failed; other address may succeed
SolaX: reading serial number from address 0x300 failed; other address may succeed

Logger: custom_components.solax_modbus.plugin_solax
Zdroj: custom_components/solax_modbus/plugin_solax.py:68
integrace: SolaX Inverter Modbus ([dokumentace](https://homeassistant-solax-modbus.readthedocs.io/), [problémy](https://github.com/wills106/homsassistant-solax-modbus/issues))
První výskyt: 15:41:13 (2 výskyty)
Naposledy logováno: 15:41:18

SolaX: attempt to read serialnumber failed at 0x0 data: None
SolaX: attempt to read serialnumber failed at 0x300 data: None
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/plugin_solax.py", line 68, in async_read_serialnr
    inverter_data = await hub.async_read_holding_registers(unit=hub._modbus_addr, address=address, count=7)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 482, in async_read_holding_registers
    resp = await self._client.read_holding_registers(address, count, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 175, in async_execute
    resp = await asyncio.wait_for(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Client is not connected

**Comment by JaroslavHorky** [comment]
So pulling out and putting back the USB dongle helped.
