### ISSUE TITLE
Number entity refactoring of homeassistant released too early - docker stable not yet supported

### ISSUE THREAD

**Issue by gelse** [wills106/homeassistant-solax-modbus#93]
i upgraded the integration via HACS today a few minor versions (to: 0.5.12 from: 0.5.something_sorry_dont_remember) which completely broke it.

what i did (i try to remember):
- upgrade to 0.5.12
- integration was broken (did not load on startup)
    - __init__() got an unexpected keyword argument 'native_min_value' in the log files
- tried to remove the integration, which failed with the same error
- tried to remove the configuration via GUI, which failed with the same error
- manually removed the integration via manipulating the .storage folder according to some other post here
- removed the solax folder in custom_components
- removed the configuration via GUI
- re-installed the integration via HACS (worked)
- tried to add new configuration via GUI which again failed with the same error as above (did not even start the GUI)
all of the above with a few restarts/reloads of home assistant in between.

now i am out of ideas...

system information:
home assistant running in docker
Solax Inverter X3-Hybrid-8.0-D with Modbus-over-TCP

error in the logfile:

```
2022-08-01 06:08:30 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.solax_modbus.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 603, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 620, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/solax_modbus/__init__.py", line 19, in <module>
    from .const import GEN2, GEN3, GEN4, X1, X3, HYBRID, AC, EPS, PV
  File "/config/custom_components/solax_modbus/const.py", line 225, in <module>
    SolaxModbusNumberEntityDescription( name = "Battery Minimum Capacity",
TypeError: __init__() got an unexpected keyword argument 'native_min_value'
2022-08-01 06:08:30 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration solax_modbus: Exception importing custom_components.solax_modbus.config_flow
```

is there anything else of information that i can provide ?

**Comment by gelse** [comment]
from what i see it as something to do with NumberEntityDescription from homeassistand itself ... wtf...
i am using core 2022.5.5

**Comment by gelse** [comment]
switching to the linuxserver.io image fixed the issue (but opened new, different problems with other components).

guys, if i am not completely mistaken and somehow missed the stable tagged image - this is not cool. and yes, i know, but i did NOT check the "show beta versions" flag when installing the solax_modbus integration.

**Comment by gelse** [comment]
relevant issue: https://github.com/wills106/homeassistant-solax-modbus/issues/84

**Comment by gelse** [comment]
additional information:
the image i used was
ghcr.io/home-assistant/home-assistant:stable
which - from whatever reason - does not seem to exist any more, despite being the one that gets promoted in the home-assistant installation documentation.

man, they fucked that up ...

and you are completely innocent and i will now close this issue.

**Comment by wills106** [comment]
You are correct Release [0.5.9](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.9) Introduced the change to comply with the refactoring that was needed to comply with HA 2022.7 (With the old formatting being dropped by HA 2022.10)

Release [0.5.11](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.11) was needed to address another issue relating to sensors with scaling, I think this is another issue related to HA 2022.7

Release [0.5.12](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/0.5.12) was needed to clean-up the codebase from 0.5.11 & 0.5.11a due to a number of issues relating to how the code got updated to GitHub.

**Comment by wills106** [comment]
I have also added a section to the README.md under Known Issues.
