### ISSUE TITLE
[Bug]: Automations stop and ignore 'continue_on_error': Thrown ModbusIOException not handled and converted to HomeAssistantError

### ISSUE THREAD

**Issue by cschlipf** [wills106/homeassistant-solax-modbus#937]
### Describe the bug

With the current version of the plugin I frequently get errors when setting values. See also #801 and #804. E.g. "Modbus Error: [Connection] Client is not connected" or "pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request". or "Error: Modbus Error: [Input/Output] ERROR: No response received after 3 retries".

Now I can ignore these errors. The integration is working nevertheless. So far so good.

However the problem is when I am using the plugin in an automation. Even though I have set 'continue_on_error:true' it stops the automation and does not continue:
<img width="662" alt="image" src="https://github.com/wills106/homeassistant-solax-modbus/assets/894150/ef2a47df-775f-4b04-acfc-b21426d2ac88">

The reason why 'continue_on_error' is not working properly here is because the ModBusIOException is not caught and not converted to an instance of a HomeAssistantError. Proposal to fix this problem is to catch 'ModBusIOException' and throw an IntegrationError (subclass of HomeAssistantError) instead (see https://github.com/home-assistant/core/blob/826587abb265e4a16142893587130ef0203671d5/homeassistant/exceptions.py#L200)

### Integration Version

2024.05.7

### Homeassistant core version

2024.6.1

### Inverter brand

Sofar HYD 10 KTL

### Plugin used

plugin_sofar.py

### Serial prefix

SP2ES1

### Connection Method

LSE-3

### Detailed Error Log

File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 723, in async_trigger
return await self.action_script.async_run(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1773, in async_run
return await asyncio.shield(create_eager_task(run.async_run()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
await self._async_step(log_exceptions=False)
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
self._handle_exception(
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 581, in _handle_exception
raise exception
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
await getattr(self, handler)()
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
response_data = await self._async_run_long_action(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
return await long_task
^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 191, in async_handle_select_option
await self.async_select_option(option)
File "/config/custom_components/solax_modbus/select.py", line 100, in async_select_option
await self._hub.async_write_registers_single(unit=self._modbus_addr, address=self._register, payload=payload)
File "/config/custom_components/solax_modbus/__init__.py", line 548, in async_write_registers_single
resp = await self._client.write_registers(address, payload, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 183, in async_execute
raise ModbusIOException(
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] ERROR: No response received after 3 retries
2024-06-23 13:56:00.225 INFO (MainThread) [gql.transport.websockets] <<< {"id":"1","type":"next","payload":{"data":{"liveMeasurement":{"accumulatedConsumption":10.7407,"accumulatedConsumptionLastHour":0,"accumulatedCost":2.025997,"accumulatedProduction":0.3237,"accumulatedProductionLastHour":0,"accumulatedReward":null,"averagePower":770.7,"currency":"EUR","currentL1":null,"currentL2":null,"currentL3":null,"lastMeterConsumption":2450,"lastMeterProduction":5941,"maxPower":910,"minPower":0,"power":367,"powerFactor":null,"powerProduction":null,"powerReactive":null,"signalStrength":null,"timestamp":"2024-06-23T13:55:59.000+02:00","voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null}}}}
2024-06-23 13:56:01.390 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-06-23 13:56:01.390 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed. (None)
Traceback (most recent call last):
File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 1017, in _read_ready__data_received
self._protocol.data_received(data)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 302, in data_received
self.datagram_received(data, None)
File "/usr/local/lib/python3.12/site-packages/pymodbus/transport/transport.py", line 336, in datagram_received
cut = self.callback_data(self.recv_buffer, addr=addr)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pymodbus/client/base.py", line 207, in callback_data
self.framer.processIncomingPacket(data, self._handle_response, slave=0)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/base.py", line 139, in processIncomingPacket
self.frameProcessIncomingPacket(single, callback, slave, **kwargs)
File "/usr/local/lib/python3.12/site-packages/pymodbus/framer/socket_framer.py", line 112, in frameProcessIncomingPacket
raise ModbusIOException("Unable to decode request")
pymodbus.exceptions.ModbusIOException: Modbus Error: [Input/Output] Unable to decode request
2024-06-23 13:56:01.805 ERROR (MainThread) [pymodbus.logging] General exception: unpack requires a buffer of 4 bytes
2024-06-23 13:56:01.806 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed. (None)

**Comment by cschlipf** [comment]
@wills106 - I am currently working on a fix for this
