### ISSUE TITLE
[Bug]: Slow Update Interval after Firmware Update on Solax X3 MiC G2

### ISSUE THREAD

**Issue by treimy** [wills106/homeassistant-solax-modbus#965]
### Describe the bug

I had Firmware Version fo the SolaX X3 MiX G2: ARM: 128 DSP: 125 with the WiFi/LAN Stick
Then I've got Update from SolaX to ARM: 129 DSP: 127

After that Update my Entities only Updates every several minutes. Sometimes it takes 15 minutes to update an entity.
I hav etried to restart the Inverter, restart the Stick. Delete the Integration. All of them together, but nothing helps.
 

### Integration Version

2024.05.7

### Homeassistant core version

2024.6.4

### Inverter brand

Solax X3 MiC G2

### Plugin used

plugin_solax.py

### Serial prefix

MC208TI

### Inverter firmware versions

ARM 129 DSP 127

### Connection Method

Solax Pocket WiFi/LAN

### Dongle firmware

02.09

### Detailed Error Log

2024-07-25 09:31:32.001 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:00.490 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:05.498 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:10.506 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:45.673 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:50.680 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:33:55.688 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:34:20.705 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:34:25.714 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:34:30.727 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:34:35.734 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:34:40.743 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:36:41.284 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:36:46.291 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:37:31.323 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:37:36.331 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:37:36.436 WARNING (MainThread) [pymodbus.logging] Failed to connect 
2024-07-25 09:38:01.349 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:38:26.367 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:38:51.387 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:39:16.436 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:39:41.475 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:40:06.499 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:40:31.579 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:41:16.630 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:41:26.647 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:41:51.700 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:45:12.574 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:45:17.628 ERROR (MainThread) [pymodbus.logging] Cancel send, because not connected!
2024-07-25 09:45:26.385 WARNING (MainThread) [pymodbus.logging] Failed to connect

**Comment by treimy** [comment]
![solax](https://github.com/user-attachments/assets/155ef3c6-9981-40e4-8803-19fc84cadc64)

**Comment by treimy** [comment]
`Protokolldetails (WARNUNG)
Logger: homeassistant.util.loop
Quelle: util/loop.py:84
Erstmals aufgetreten: 02:50:32 (2 Vorkommnisse)
Zuletzt protokolliert: 02:50:57

Detected blocking call to open inside the event loop by custom integration 'solax_modbus' at custom_components/solax_modbus/__init__.py, line 332: fp = open(self._hass.config.path(f"{self.name}_data.json")) (offender: /config/custom_components/solax_modbus/__init__.py, line 332: fp = open(self._hass.config.path(f"{self.name}_data.json"))), please create a bug report at https://github.com/wills106/homsassistant-solax-modbus/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/solax_modbus/__init__.py", line 377, in _refresh await self.async_refresh_modbus_data(grp, _now) File "/config/custom_components/solax_modbus/__init__.py", line 403, in async_refresh_modbus_data update_result = await self.async_read_modbus_data(group) File "/config/custom_components/solax_modbus/__init__.py", line 619, in async_read_modbus_data res = await self.async_read_modbus_registers_all(group) File "/config/custom_components/solax_modbus/__init__.py", line 795, in async_read_modbus_registers_all self.loadLocalData() File "/config/custom_components/solax_modbus/__init__.py", line 332, in loadLocalData fp = open(self._hass.config.path(f"{self.name}_data.json"))`

**Comment by treimy** [comment]
Protokolldetails (WARNUNG)
Logger: pymodbus.logging
Quelle: runner.py:190
Erstmals aufgetreten: 08:08:54 (3696 Vorkommnisse)
Zuletzt protokolliert: 08:29:21

Failed to connect [Errno 111] Connect call failed ('192.168.0.10', 502)
Failed to connect

**Comment by treimy** [comment]
Short feedback, I have also an Wifi 3.0 Dongle. With this Dongle I don't have such issues. So it seems to be a problem with the LAN/Wifi Dongle. I have contacted SolaX Support but haven't got any response yet.

**Comment by treimy** [comment]
I have got a new firmware for the LAN/Wi-Fi Stick. With this firmware I don't have any of these problems anymore
